### ISSUE TITLE
builder on nittro.org fails with 500

### ISSUE THREAD

**Issue by xpavp03** [nittro/nittro#42]
Steps to reproduce:

1. https://www.nittro.org/download
2. enter this into Bootstrap Options:
```
params:
    page:
        whitelistLinks: true
extensions:
services:
factories:
```
3. click Download Custom Build

This error shows up:
There was an error processing your request. Please try again later.

In browser Dev Tools I see response status 500 Internal Server Error.
